---
- name: Ensure HAProxy is installed.
  dnf: 
    name: haproxy 
    state: present

- name: Generate HAProxy configuration
  template:
    src: haproxy.conf.j2
    dest: /etc/haproxy/haproxy.conf
  notify:
    - Restat HAProxy

- name: Generate keepalived
  import_tasks:
    file: keepalived.yml
