---
- name: Ensure HAProxy is installed.
  dnf: 
    name: haproxy 
    state: present

- name: Call Certificate Role
  include_role:
    name: "certificates"

- name: Generate HAProxy configuration
  template:
    src: haproxy.conf.j2
    dest: /etc/haproxy/haproxy.conf
  notify:
    - Restat HAProxy