- name: Configure Task
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - vault.yml
  tasks:
    - name: Import apache Role
      import_role:
        name: "apache"
      when: "'webserver' in group_names"
    - name: Import haproxy Role
      import_role:
        name: "haproxy"
      when: "'haproxy' in group_names"
