---
- name: Ensure cryptography Packages Installed
  pip:
    name: cryptography>=1.6
    state: present

- name: Generate private key
  community.crypto.openssl_privatekey_pipe:
  register: host_private_key

- name: debug
  debug:
    msg: "IP:{{ inventory_hostname }},{{ subjet_alt_names | default('') }}"

- name: Generate CSR
  community.crypto.openssl_csr_pipe:
    privatekey_content: "{{ host_private_key.privatekey }}"
    common_name: "{{ ansible_fqdn }}"
    subject_alt_name: "IP:{{ inventory_hostname }}{{ ',' if subjet_alt_names is defined }}{{ subjet_alt_names | default('') }}"
    subject_alt_name_critical: true
    organization_name: "{{ organization_details.name }}"
    locality_name: "{{ organization_details.locality }}"
    country_name: "{{  organization_details.country  }}"
  register: host_csr

- name: Sign the CSR using the CA
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ host_csr.csr }}"
    ownca_path: /etc/ca/ca.crt
    ownca_privatekey_path: /etc/ca/private/ca.key
    provider: ownca
  register: host_crt
  delegate_to: localhost

- name: Ensure /etc/ssl/private directory exists
  file:
    path: /etc/ssl/private/
    state: directory
    mode: 0700


- name: Assemble private key and certificate into PEM file
  copy:
    content: "{{ host_private_key.privatekey }}{{ host_crt.certificate }}"
    dest: /etc/ssl/private/server.pem
    mode: 0600
  notify: "{{ handler_to_notify }}"

- name: Copy certificate to trusted anchors directory
  copy:
    src: /etc/ca/ca.crt
    dest: /etc/pki/ca-trust/source/anchors/root-CA.crt
    mode: 0644

- name: Update CA trust on the host
  command: update-ca-trust
