---
- name: Ensure cryptography Packages Installed
  pip:
    name: cryptography>=1.6
    state: present

- name: Generate private key
  community.crypto.openssl_privatekey_pipe:
  register: host_private_key

- name: Generate CSR
  community.crypto.openssl_csr_pipe:
    privatekey_content: "{{ host_private_key.privatekey }}"
    common_name: "{{ ansible_fqdn }}"
    organization_name: "My Organization"
    locality_name: "Tel Aviv"
    country_name: "IL"
  register: host_csr

- name: Sign the CSR using the CA
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ host_csr.csr }}"
    ownca_path: /etc/ca/ca.crt
    ownca_privatekey_path: /etc/ca/private/ca.key
    provider: ownca
  delegate_to: localhost
  register: host_crt

- name: Ensure /etc/ssl/private/server.pem directory exists
  file: /etc/ssl/private/
  state: directory
  mode: '0755'


- name: Assemble private key and certificate into PEM file
  copy:
    content: "{{ host_private_key.privatekey }}{{ host_crt.certificate }}"
    dest: /etc/ssl/private/server.pem